title: Makena Portfolio
description: Makena Howat's programming portfolio
theme: just-the-docs
color_scheme: custom

url: https://MakenaH.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
